# Project settings fo CI

run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 1m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: false

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: false

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  # default is "colored-line-number"
  format: github-actions

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

  # make issues output unique by line, default is true
  uniq-by-line: true

  # add a prefix to the output file references; default is no prefix
  path-prefix: ""

  # sorts results by: filepath, line and column
  sort-results: false

# список линтеров
linters:
  disable-all: true
  enable:
  - gofmt # форматирование кода (пробелы, отступы, скобки)
  - goimports # обновление списка imports
  - govet # общий анализ возможных багов
  - goconst # нахождение строк, которые следует вынести в константы
  - funlen # детектирование слишком крупных функций
  - bodyclose # проверка на незакрытые body после чтения тела ответа
  - errcheck # проверка на обработку всех ошибок
  - deadcode # детектирование не использованного кода
  - exportloopref # детектирование экспорта указателя на переменную внутри цикла

# настройки отдельных линтеров
linters-settings:
  goimports:
  # указываем префикс локальных импортов, они будут группироваться
  local-prefixes: path/to/module
  govet:
  # проверка на использование переменных «в тени»
  check-shadowing: true
  goconst:
  # goconst находит строки не меньше 2 символов, которые встречаются хотя бы 2 раза
  min-len: 2
  min-occurrences: 2
  funlen:
  # функция помечается длинной если она больше 100 строк кода либо больше 50 операций
  lines: 100
  statements: 50